name: Build and Push v3

on:
  workflow_dispatch:
  pull_request:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Marauder Binaries v3 for s3 zero
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
#      - name: Install ESP32 Boards and Compile TestFile
#        uses: ArminJo/arduino-test-compile@v3.2.1
#        with:
#          sketch-names: TestFile.ino
#          arduino-board-fqbn: esp32:esp32:esp32s2
#          platform-url: https://github.com/espressif/arduino-esp32/releases/download/2.0.10/package_esp32_dev_index.json
          
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "/home/runner/work/ESP32Marauder/ESP32Marauder/bin" >> $GITHUB_PATH
          export PATH=$PATH:/home/runner/work/ESP32Marauder/ESP32Marauder/bin
          arduino-cli version

      - name: Install Arduino-ESP32 Core v2.0.11
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@2.0.11

      - name: Verify Installed Cores
        run: arduino-cli core list

      - name: Build TestFile with ESP32 v2.0.11
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: TestFile.ino
          arduino-board-fqbn: esp32:esp32:esp32s2
          arduino-platform: esp32:esp32@2.0.11
          platform-url: https://github.com/espressif/arduino-esp32/releases/download/2.0.11/package_esp32_dev_index.json

      - name: Verify Installed Cores Again
        run: arduino-cli core list
          
      - name: Show Arduino dir structure
        run: |
          find /home/runner/.arduino15/packages/esp32/hardware/
        
#      - name: Pull arduino-esp32 v2.0.4
#        uses: actions/checkout@v4
#        with:
#          repository: espressif/arduino-esp32
#          ref: 2.0.4
#          path: 2.0.4arduino-esp32
          
#      - name: Pull arduino-esp32 v2.0.10
#        uses: actions/checkout@v4
#        with:
#          repository: espressif/arduino-esp32
#          ref: 2.0.10
#          path: 2.0.10
          
      - name: Install AsyncTCP
        uses: actions/checkout@v4
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomAsyncTCP
          
      - name: Install MicroNMEA
        uses: actions/checkout@v4
        with:
          repository: stevemarple/MicroNMEA
          ref: v2.0.6
          path: CustomMicroNMEA
          
      - name: Install ESPAsyncWebServer
        uses: actions/checkout@v4
        with:
          repository: bigbrodude6119/ESPAsyncWebServer
          ref: master
          path: CustomESPAsyncWebServer
          
      - name: Install TFT_eSPI
        uses: actions/checkout@v4
        with:
          repository: Bodmer/TFT_eSPI
          ref: V2.5.34
          path: CustomTFT_eSPI

      - name: Install lv_arduino
        uses: actions/checkout@v4
        with:
          repository: lvgl/lv_arduino
          ref: 3.0.0
          path: Customlv_arduino

      - name: Install JPEGDecoder
        uses: actions/checkout@v4
        with:
          repository: Bodmer/JPEGDecoder
          ref: 1.8.0
          path: CustomJPEGDecoder

      - name: Install NimBLE-Arduino
        uses: actions/checkout@v4
        with:
          repository: h2zero/NimBLE-Arduino
          ref: 1.4.1
          path: CustomNimBLE-Arduino

      - name: Install Adafruit_NeoPixel
        uses: actions/checkout@v4
        with:
          repository: adafruit/Adafruit_NeoPixel
          ref: 1.10.7
          path: CustomAdafruit_NeoPixel

      - name: Install ArduinoJson
        uses: actions/checkout@v4
        with:
          repository: bblanchon/ArduinoJson
          ref: v6.18.2
          path: CustomArduinoJson

      #- name: Install SwitchLib
      #  uses: actions/checkout@v4
      #  with:
      #    repository: justcallmekoko/SwitchLib
      #    ref: main
      #    path: CustomSwitchLib
          
      - name: Install LinkedList
        uses: actions/checkout@v4
        with:
          repository: ivanseidel/LinkedList
          ref: v1.3.3
          path: CustomLinkedList
          
      - name: Install EspSoftwareSerial
        uses: actions/checkout@v4
        with:
          repository: plerup/espsoftwareserial
          ref: 8.1.0
          path: CustomEspSoftwareSerial
          
      - name: Install Adafruit_BusIO
        uses: actions/checkout@v4
        with:
          repository: adafruit/Adafruit_BusIO
          ref: 1.15.0
          path: CustomAdafruit_BusIO
          
      - name: Install Adafruit_MAX1704X
        uses: actions/checkout@v4
        with:
          repository: adafruit/Adafruit_MAX1704X
          ref: 1.0.2
          path: CustomAdafruit_MAX1704X
          
      #- name: Search for SD lib in arduino-esp32 v2.0.4
      #  run: |
      #    find /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.4arduino-esp32 -name "SD"
          
      - name: Configure TFT_eSPI
        run: |
          rm -f CustomTFT_eSPI/User_Setup_Select.h
          cp User_Setup_Select.h CustomTFT_eSPI/
          cp User_Setup_marauder_mini.h CustomTFT_eSPI/
          cp User_Setup_og_marauder.h CustomTFT_eSPI/
          cp User_Setup_marauder_m5stickc.h CustomTFT_eSPI/
          cp User_Setup_marauder_rev_feather.h CustomTFT_eSPI/
          cp User_Setup_dual_nrf24.h CustomTFT_eSPI/
          pwd
          ls -la
          ls -la CustomTFT_eSPI
          
      #- name: Place 2.0.10 for use
      #  run: |
      #    mkdir -p /home/runner/.arduino15/packages/esp32/hardware/esp32/
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.3 /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.3
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/
      #    echo Whoever made me have to do this can fuck off
          
      #- name: Replace arduino-esp32 v2.0.10 that was gloriously forced on us
      #  run: |
      #    rm -rf /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.3 /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.3
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/
      #    echo Whoever made me have to do this can fuck off
          
      #- name: Search for SD lib in arduino-esp32
      #  run: |
      #    find /home/runner/ -name "SD"
          
      #- name: Replace SD lib
      #  run: |
      #    rm -rf /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.4arduino-esp32/libraries/SD /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
          
      - name: Modify platform.txt
        run: |
          for i in $(find /home/runner/.arduino15/packages/esp32/hardware/esp32/ -name "platform.txt"); do
            sed -i 's/compiler.c.elf.libs.esp32c3=/compiler.c.elf.libs.esp32c3=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32s3=/compiler.c.elf.libs.esp32s3=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32s2=/compiler.c.elf.libs.esp32s2=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32=/compiler.c.elf.libs.esp32=-zmuldefs /' "$i"
            cat "$i" | grep compiler.c.elf.libs.esp32c3
            cat "$i" | grep compiler.c.elf.libs.esp32s3
            cat "$i" | grep compiler.c.elf.libs.esp32s2
            cat "$i" | grep compiler.c.elf.libs.esp32
          done

      - name: Configure configs.h for Flipper Zero ESP32_S3ZERO
        run: |
            sed -i 's/^  #define MARAUDER_REV_FEATHER/  \/\/#define MARAUDER_REV_FEATHER/' esp32_marauder/configs.h
            sed -i 's/^  #define MARAUDER_M5STICKC/  \/\/#define MARAUDER_M5STICKC/' esp32_marauder/configs.h
            sed -i 's/^  #define MARAUDER_MINI/  \/\/#define MARAUDER_MINI/' esp32_marauder/configs.h
            sed -i 's/^  #define MARAUDER_V4/  \/\/#define MARAUDER_V4/' esp32_marauder/configs.h
            sed -i 's/^  #define MARAUDER_V6/  \/\/#define MARAUDER_V6/' esp32_marauder/configs.h
            sed -i 's/^  #define MARAUDER_V6_1/  \/\/#define MARAUDER_V6_1/' esp32_marauder/configs.h
            sed -i 's/^  #define MARAUDER_V7/  \/\/#define MARAUDER_V7/' esp32_marauder/configs.h
            sed -i 's/^  #define MARAUDER_KIT/  \/\/#define MARAUDER_KIT/' esp32_marauder/configs.h
            sed -i 's/^  #define GENERIC_ESP32/  \/\/#define GENERIC_ESP32/' esp32_marauder/configs.h
            sed -i 's/^  \/\/#define ESP32_S3/  #define ESP32_S3/' esp32_marauder/configs.h
            sed -i 's/^  #define MARAUDER_FLIPPER/  \/\/#define MARAUDER_FLIPPER/' esp32_marauder/configs.h
            sed -i 's/^  #define ESP32_LDDB/  \/\/#define ESP32_LDDB/' esp32_marauder/configs.h
            sed -i 's/^  #define MARAUDER_DEV_BOARD_PRO/  \/\/#define MARAUDER_DEV_BOARD_PRO/' esp32_marauder/configs.h
            
      - name: Build Marauder for Flipper Zero ESP32_S3ZERO
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: esp32_marauder.ino
          arduino-board-fqbn: esp32:esp32:esp32s3:PartitionScheme=min_spiffs,FlashSize=4M,PSRAM=enabled
          extra-arduino-cli-args: "--warnings none"
          arduino-platform: esp32:esp32@2.0.11
          platform-url: https://github.com/espressif/arduino-esp32/releases/download/2.0.11/package_esp32_dev_index.json
          
      - name: Rename Marauder ESP32_S3ZERO bin
        run: |
          mv ./esp32_marauder/build/esp32.esp32.esp32s3/esp32_marauder.ino.bin ./esp32_marauder/build/esp32.esp32.esp32s3/esp32_marauder.esp32_s3_zero.bin
          
      - name: Display finished bins
        run: |
          find ./esp32_marauder/build -name "*.bin"

      - name: 'Upload ESP32_S3ZERO Artifact'
        uses: actions/upload-artifact@v3
        with:
              name: esp32_marauder.esp32_s3.bin
              path: ./esp32_marauder/build/esp32.esp32.esp32s3/esp32_marauder.esp32_s3_zero.bin
              retention-days: 5

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
        if: github.event_name != 'pull_request'

      - name: Upload esp32_s3 Asset
        id: upload-esp32_s3-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./esp32_marauder/build/esp32.esp32.esp32s3/esp32_marauder.esp32_s3_zero.bin
          asset_name: esp32_marauder.esp32_s3_zero.bin
          asset_content_type: application/bin
        if: github.event_name != 'pull_request'